db:
	images: klaemo/couchdb:2.0.0
	ports:
	- "5984:5984"
	environment:
	- COUCHDB_USER=mariusz
	- COUCHDB_PASSWORD=123456

app:
	image: ibmcom/swift-ubuntu
	ports:
	- "8080:8080"
	volumes:
	- .:/root/FoocTruckAPI
	command: bash -c "cd /root/FooTruvkAPI && swift build --clean && swift build --configuration release && ./.build/release/FoodTruckServer"
links:
	- db:localhost
